name: unifi-network

networks:
  ipnet4:
    external: true
  unifiNwBend:
    internal: true
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2

services:
  unifi-db1:
    image: docker.io/mongo:7-jammy
    volumes:
      - stack-volume2:/data/db
      - stack-volume3:/data/configdb
      - /docker-compose/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      unifiNwBend:
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    depends_on:
      - unifi-db1
    networks:
      ipnet4:
        ipv4_address: 192.168.4.230
      unifiNwBend:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db1
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - stack-volume1:/config
    restart: unless-stopped

volumes:
  stack-volume1:
  stack-volume2:
  stack-volume3:
